# Generated by Django 2.2.2 on 2019-06-14 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMasa',
            fields=[
                ('id_tipo_masa', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_tipo', models.CharField(max_length=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='id',
        ),
        migrations.AddField(
            model_name='pizza',
            name='ingrediente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pi.Ingrediente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='ingrediente_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='pizza_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
