# Generated by Django 2.2.2 on 2019-06-16 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pi', '0002_auto_20190613_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cod_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nom_cliente', models.CharField(max_length=40)),
                ('dir_cliente', models.CharField(max_length=100)),
                ('tel_cliente', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('cod_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_empleado', models.CharField(max_length=40)),
                ('password_empleado', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('cod_pedido', models.IntegerField(primary_key=True, serialize=False)),
                ('fec_pedido', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='tipomasa',
            old_name='id_tipo_masa',
            new_name='tipo_masa_id',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='ingrediente',
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('cod_registro', models.AutoField(primary_key=True, serialize=False)),
                ('cod_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pi.Cliente')),
                ('cod_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pi.Empleado')),
                ('cod_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pi.Pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Hecha_De',
            fields=[
                ('corr_hec_de', models.AutoField(primary_key=True, serialize=False)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pi.Ingrediente')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pi.Pizza')),
                ('tipomasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pi.TipoMasa')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Pedido',
            fields=[
                ('corr_det_ped', models.AutoField(primary_key=True, serialize=False)),
                ('cant_pedido', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pi.Pedido')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pi.Pizza')),
            ],
        ),
    ]
